#sudo lxc-destroy -n scale_dgw3
#sudo  lxc-destroy -n scale_dgw4
#sudo lxc-destroy -n scale_sgw3_1
#sudo  lxc-destroy -n scale_sgw3_2
#sudo lxc-destroy -n scale_sgw4_1
#sudo  lxc-destroy -n scale_sgw4_2
sudo lxc-clone dgw2 dgw3
sudo lxc-clone dgw2 dgw4
sudo lxc-clone sgw2 sgw3
sudo lxc-clone sgw2 sgw4
